### ISSUE TITLE
Exception when run DownloadNewsPanel class.

### ISSUE THREAD

**Issue by eltonnuness** [leonarduk/unison#110]
StackTrace: 
java.lang.NullPointerException
	at uk.co.sleonard.unison.input.HeaderDownloadWorker.<init>(HeaderDownloadWorker.java:92)

**Comment by leonarduk** [comment]
Hi Elton,  can you give more context?

What is calling this?

What is the full stack trace?

**Comment by eltonnuness** [comment]
Hi Steve,

the full stack trace is:

java.lang.NullPointerException
	at uk.co.sleonard.unison.input.HeaderDownloadWorker.<init>(HeaderDownloadWorker.java:92)
	at uk.co.sleonard.unison.UNISoNController.<init>(UNISoNController.java:146)
	at uk.co.sleonard.unison.UNISoNController.create(UNISoNController.java:105)
	at uk.co.sleonard.unison.gui.generated.UNISoNTabbedFrame.<init>(UNISoNTabbedFrame.java:110)
	at uk.co.sleonard.unison.gui.generated.DownloadNewsPanel.lambda$0(DownloadNewsPanel.java:119)
	at uk.co.sleonard.unison.gui.generated.DownloadNewsPanel$$Lambda$1/1775282465.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by eltonnuness** [comment]
In splashscreen the program crash.

**Comment by eltonnuness** [comment]
Steve,

I update my project with your last commits, now the program running normally.

Thank you

**Comment by eltonnuness** [comment]
Solved!

**Comment by leonarduk** [comment]
Hi Elton, does this mean you were merging in my feature branch into yours? You shouldn't do that. Only merge changes once in master. That's why we work in branches to not affect others work

**Comment by eltonnuness** [comment]
Oh Right, Ok, sorry my mistake

**Comment by eltonnuness** [comment]
Later I revert the changes in my branch (#8 improve gui) to old commit.

**Comment by leonarduk** [comment]
If it's breaking things then yes, revert

**Comment by eltonnuness** [comment]
Yes, Is better.

**Comment by leonarduk** [comment]
The idea is that I can push things in this branch and have travis run its build and any tests etc then if I am happy then I can merge to master.  I might still break something but it should happen less often.  It looks like you might have merged in code that actually broken in the the branch build as it was fixed in the next one.

**Comment by leonarduk** [comment]
So only merge in from master
